name = "RandomSplit"
uuid = "4f75ad7f-53e1-4703-a57b-ee35418d6f20"
authors = ["Olivier Verdier"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
